### ISSUE TITLE
Style tag in .html and .vue file

### ISSUE THREAD

**Issue by mrleblanc101** [liuderchi/ide-css#14]
Hi, 

It would be nice if the plugin supported ```<style>``` tag inside .htm, .php or .vue (single file component).
I tried adding them as ```Additional grammars (experimental)``` to no luck.

I understand that outline view would not work in those case as these file type already use the outline view for other purpose, but it would be nice to still see the CSS propriety tooltip description.

**Comment by liuderchi** [comment]
@mrleblanc101 currently [ide-html](https://atom.io/packages/ide-html) supports this:

when you have this html with inline `<script>`
```html
<!DOCTYPE html>
<html>
<head>
  <style media="screen">
    .App {
      font-family: serif;
    }
  </style>
</head>
<body>
  <p>hello</p>
</body>
</html>

```

and you move mouse over the `serif` text, a tooltip would show up.

**Comment by mrleblanc101** [comment]
Still...
Won't work for .php and .vue file.
I guess there are many other file type that it also won't work for.
We should be able to add any file type in the settings and then the plugin would just have to look for ```<style>``` (and not <script> like you mentioned) tags or proprieties keyword like (display, background-colo, border, etc).

**Comment by liuderchi** [comment]
@mrleblanc101 so is it working for `*.html` files on your environment?


> ... not <script> like you mentioned

It was my typo. I meant `<style>`.

> We should be able to add any file type in the settings and then the plugin would just have to look for <style> ... tags

It is a limitation of language server to parse any kind of grammar. So this feature is currently experimental.

**Comment by richiksc** [comment]
I use the ide-vue package for Vue support.
