### ISSUE TITLE
Multiple conditions in @supports show weird errors

### ISSUE THREAD

**Issue by LeaVerou** [liuderchi/ide-css#23]
This is a reduced code snippet that errors:

```css
@supports (caret-color) and (color) {
	
}
```

The error is `) expected`.

**Comment by liuderchi** [comment]
@LeaVerou thanks for reporting!
This is also related to #7.

Will report to language server repo.

**Comment by liuderchi** [comment]
UPDATE:
this modified snippet is passing validation

```css
@supports (caret-color: red) and (color: green) {

}
```

**Comment by LeaVerou** [comment]
It actually works with my real code as well now. The value-less conditions are probably invalid, not sure where I got those from, lol. Closing issue, thanks for the quick response!
