### ISSUE TITLE
Sass?

### ISSUE THREAD

**Issue by louie90** [liuderchi/ide-css#4]
Will there be Sass support? only scss works..

**Comment by liuderchi** [comment]
@louie90 It depends on vscode group future development.

Currently it looks lik [`vscode-css-languageserver`][langserver] (this package basing on) supports only [these 3 file extensions](https://github.com/vscode-langservers/vscode-css-languageserver/blob/master/src/cssServerMain.ts#L20-L22) right now.

Also latest [vscode extension](https://github.com/Microsoft/vscode/tree/master/extensions) has only those grammars: [css][css], [less][less], [scss][scss]

[langserver]: https://github.com/vscode-langservers/vscode-css-languageserver "langserver"
[css]: https://github.com/Microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json#L8 "css"
[less]: https://github.com/Microsoft/vscode/blob/master/extensions/less/syntaxes/less.tmLanguage.json#L9 "less"
[scss]: https://github.com/Microsoft/vscode/blob/master/extensions/scss/syntaxes/scss.json#L8 "scss"
