### ISSUE TITLE
Nested @supports shows errors

### ISSUE THREAD

**Issue by craigmdennis** [liuderchi/ide-css#7]
`Atom: 1.21.0`
`ide-css: 0.2.0`

I'm not sure if this is a bug or a feature (and the errors are pointing out that I'm using `@supports` incorrectly). But the resulting CSS is correct and behaves as expected.

I have the following LESS code:

```.less
.PermissionRoles {
  &__list {
    @supports (display: grid) {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      grid-gap: 16px;
    }

    @supports not (display: grid) {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      margin-left: -8px;
      margin-right: -8px;
    }
  }
}
```

IDE-CSS is reporting:
`) expected` on line 3
`{ expected` on lines 10-14
`at-rule or selector expected` on line 16

<img width="410" alt="screenshot 2017-10-07 21 14 55" src="https://user-images.githubusercontent.com/725067/31311464-97742d24-aba4-11e7-970b-4125b8cb49be.png">

**Comment by LeaVerou** [comment]
How is this an enhancement? That seems as clearly a bug as one can get.

**Comment by liuderchi** [comment]
@LeaVerou thanks for correction.

I used wrong version of validator and thought `@supports ...`  is not part of standard.

**Comment by liuderchi** [comment]
@craigmdennis Is this still happens in latest release (v0.3.0)?

**Comment by craigmdennis** [comment]
> Is this still happens in latest release (v0.3.0)?

It appears to be working correctly in `0.3.0`
